### ISSUE TITLE
Bug with `globe -s`

### ISSUE THREAD

**Issue by arjpeg** [adamsky/globe#1]
I have successfully installed globe since I can use the `globe -i` command, but when I use `globe -s` it just gives me this error:
```
thread 'main' panicked at 'Original console mode not set', C:\Users\Owner\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.17.7\src\event\sys\windows.rs:38:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by adamsky** [comment]
Thanks, I wasn't able to test this on a windows machine yet!

The issue appears to be related to how crossterm handles the execution of `DisableMouseCapture` command on windows. I suppose I could remove that command from the screensaver mode altogether, since mouse events are ignored there anyways.

**Comment by adamsky** [comment]
https://github.com/adamsky/globe/commit/30942a9b74a8c3ff249fba4ccd9f21f8b3fe42c6 should fix this, let me know if you're still getting the same error.
