### ISSUE TITLE
Garbage input on mouse click after running interactive mode

### ISSUE THREAD

**Issue by rshamsnejad** [adamsky/globe#11]
After running `cargo run -- -i` to try the Globe, I exited by hitting `q`. After that, mouse clicks input some serious garbage in my terminal : 

     $ 0;110;32M32;110;32M32;110;32M32;109;32M32;109;33M32;108;33M32;108;33M32;108;33M32;107;34M32;106;34M32;106;34M32;105;34M32;104;35M32;103;35M32;102;35M32;100;35M32;99;35M32;97;35M32;95;34M32;93;34M32;90;34M32;88;33M32;85;32M32;82;31M32;79;31M32;77;30M32;74;29M32;72;28M32;70;27M32;68;26M32;67;25M32;66;25M32;65;24M32;65;24M32;65;24M32;65;23M32;65;23M32;65;23M32;65;23M32;66;23M32;66;23M32;66;23M0;66;23m2;86;14M2;86;14m

Reproduced on Konsole and Yakuake, with and without `tmux`. To solve it, exitting the shell is necessary.

**Comment by adamsky** [comment]
Should be fixed by https://github.com/adamsky/globe/commit/30942a9b74a8c3ff249fba4ccd9f21f8b3fe42c6.
