### ISSUE TITLE
cargo install globe-cli fails to compile

### ISSUE THREAD

**Issue by nkh** [adamsky/globe#26]
same error in:
cargo 1.69.0 (6e9a83356 2023-04-12)
rustc 1.69.0 (84c898d65 2023-04-16)

and:
rustc 1.70.0 (90c541806 2023-05-31)
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:54:18
   |
50 | /             Arg::new("interactive")
51 | |                 .short('i')
52 | |                 .long("interactive")
53 | |                 .display_order(0)
54 | |                 .about("Interactive mode (input enabled)"),
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:61:18
   |
57 | /             Arg::new("screensaver")
58 | |                 .short('s')
59 | |                 .long("screensaver")
60 | |                 .display_order(1)
61 | |                 .about("Screensaver mode (input disabled)"),
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:67:18
   |
64 | /             Arg::new("refresh_rate")
65 | |                 .short('r')
66 | |                 .long("refresh-rate")
67 | |                 .about("Refresh rate in frames per second")
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:76:18
   |
73 | /             Arg::new("globe_rotation")
74 | |                 .short('g')
75 | |                 .long("globe-rotation")
76 | |                 .about("Starting globe rotation speed")
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:85:18
   |
82 | /             Arg::new("cam_rotation")
83 | |                 .short('c')
84 | |                 .long("cam-rotation")
85 | |                 .about("Starting camera rotation speed")
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:94:18
   |
91 | /             Arg::new("cam_zoom")
92 | |                 .short('z')
93 | |                 .long("cam-zoom")
94 | |                 .about("Starting camera zoom")
   | |                 -^^^^^ method not found in `Arg<'_>`
   | |_________________|
   |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:103:18
    |
100 | /             Arg::new("focus_speed")
101 | |                 .short('f')
102 | |                 .long("focus-speed")
103 | |                 .about("Target focusing animation speed")
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:112:18
    |
109 | /             Arg::new("location")
110 | |                 .short('l')
111 | |                 .long("location")
112 | |                 .about("Starting location coordinates")
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:121:18
    |
118 | /             Arg::new("night")
119 | |                 .short('n')
120 | |                 .long("night")
121 | |                 .about("Enable displaying the night side of the globe"),
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:127:18
    |
124 | /             Arg::new("template")
125 | |                 .short('t')
126 | |                 .long("template")
127 | |                 .about("Display a built-in globe template")
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:136:18
    |
134 | /             Arg::new("texture")
135 | |                 .long("texture")
136 | |                 .about("Apply custom texture from file")
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:143:18
    |
141 | /             Arg::new("texture_night")
142 | |                 .long("texture-night")
143 | |                 .about("Apply custom night side texture from file")
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/globe-cli-0.2.0/src/main.rs:151:18
    |
148 | /             Arg::new("pipe")
149 | |                 .short('p')
150 | |                 .long("pipe")
151 | |                 .about("Read coordinates from stdin and display them on the globe"),
    | |                 -^^^^^ method not found in `Arg<'_>`
    | |_________________|
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `globe-cli` due to 13 previous errors

**Comment by charliefrance** [comment]
Same, did you find a fix?

**Comment by wade-cheng** [comment]
It's as it says on the tin, `.about` doesn't exist somehow. For some reason, there's something weird going on in the versioning where cargo decides it doesn't compile because methods are outdated (or forward-dated?). 

Pretty easily fixable by either changing `clap = { version = "3.0.0-beta.2", ...` to `clap = { version = "3.0.0", ...` in `globe-cli/Cargo.toml` and then changing all offending `.about`s to `.help`s. Or, just do the same install process with a fork that fixes this such as https://github.com/j0ru/globe.

**Comment by adamsky** [comment]
>Pretty easily fixable by either changing clap = { version = "3.0.0-beta.2", ... to clap = { version = "3.0.0", ... in globe-cli/Cargo.toml and then changing all offending .abouts to .helps. Or, just do the same install process with a fork that fixes this such as https://github.com/j0ru/globe.

I pushed this exact fix to master https://github.com/adamsky/globe/commit/4f61644e380c835e392d0ee56171e96411d5ecf1. Hopefully this won't cause any more problems for folks.
