### ISSUE TITLE
loading terminal globe to screensaver 

### ISSUE THREAD

**Issue by 007tofreedom** [adamsky/globe#27]
Hello I encountered a problem were im not able to see globe as screensaver when typing -s or globe -inc2 -g10

**Comment by adamsky** [comment]
`-s` screensaver mode is about disabling user input, as such it's opposite to the interactive mode `-i`.

If you substitute `-i` for `-s` in `globe -inc2 -g10` you should get what you want.

**Comment by 007tofreedom** [comment]
I ran globe -s then globe -s -inc2 -g10 and for some reason my screen saver
still pops up so I disabled it but still nothing but the globe is spinning
just no screen saver
